name: Tests and code
on: [ push, pull_request ]

jobs:
  testing:
    name: Drupal ${{ matrix.drupal-versions }} with PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    container: php:${{ matrix.php-versions }}-fpm-buster
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '7.4', '8.0', '8.1' ]
        drupal-versions: [ '~9.3.0', '~9.4.0' ]
    env:
      DRUPAL_CORE_CONSTRAINT: ${{ matrix.drupal-versions }}

    steps:
      - name: Checkout Coder
        uses: actions/checkout@v2
      - name: Setup Container Requirements
        run: ./tests/setup.sh
      - name: Run test
        run: ./tests/test.sh
