name: Tests and code
on: [ push, pull_request ]

jobs:
  testing:
    name: Drupal ${{ matrix.drupal-version }} with PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    container: drupal:php${{ matrix.php-version }}-fpm-buster
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.0', '8.1' ]
        drupal-version: [ '~9.4.0', '~9.5.0', '~10.0.0', '~10.1.0', '~10.2.0' ]
        exclude:
          - php-version: 8.0
            drupal-version: '~10.0.0'
          - php-version: 8.0
            drupal-version: '~10.1.0'
          - php-version: 8.0
            drupal-version: '~10.2.0'
    env:
      DRUPAL_CORE_CONSTRAINT: ${{ matrix.drupal-version }}

    steps:
      - name: Checkout Coder
        uses: actions/checkout@v2
      - name: Setup Container Requirements
        run: ./tests/setup.sh
      - name: Run test
        run: ./tests/test.sh
